import React from 'react';
import ListItem from '../ListItem/ListItem';
import S from './style.module.css';

function useForceUpdate() {
    const [i, setI] = React.useState(0);
    return () => setI(i+1)
  }


export default function List() {
    const forceUpdate = useForceUpdate()
    const [items, setItems] = React.useState([
        {
            title: 'Rocke1 Rocke1 Rocke1 Rocke 1Rocke 1Rocke 1Rocke 1Rocke 1Rocke 1Rocke 1',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '1',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '2',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '3',
            like: true,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '4',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '5',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '6',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '7',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '8',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '9',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '10',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '11',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '12',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '13',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '14',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '15',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '16',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '17',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '18',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '19',
            like: false,
        },
        {
            title: 'Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2Rocke 2',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '20',
            like: false,
        },
        {
            title: 'Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3Rocke 3',
            description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum ex eveniet doloremque qui. Vel possimus sapiente fugit, facilis cumque minus reprehenderit nemo, saepe at nulla voluptates! Doloribus voluptatem officiis corporis itaque suscipit consectetur, asperiores, rerum amet fuga dolorem corrupti labore qui obcaecati. Reiciendis expedita doloribus esse assumenda error at soluta quia, enim perferendis autem reprehenderit, commodi nam asperiores ab excepturi debitis dolores natus vel accusantium? Consectetur voluptatum doloribus consequatur molestiae illo asperiores perspiciatis quam. Nihil quam debitis optio illo repudiandae doloremque libero perspiciatis dignissimos laudantium provident mollitia accusamus eligendi exercitationem quisquam, corporis quod eius iste recusandae excepturi sed eaque enim obcaecati. Modi a beatae reprehenderit natus. Vero nesciunt temporibus exercitationem molestiae laudantium iste sint facilis, veritatis eum eligendi sunt. Accusantium doloremque possimus asperiores neque! Quod repudiandae fugit ab aspernatur deserunt facilis? Odit quibusdam vel, excepturi ratione vero veritatis inventore, dolores similique et minus tenetur provident officiis laboriosam aliquam voluptatibus quia, suscipit possimus totam eos ab autem. Numquam at totam unde, earum aperiam molestiae nostrum inventore! Qui, tempora! Deleniti, fugiat! Animi quisquam reprehenderit, exercitationem error, temporibus accusantium laborum dolorem itaque doloremque natus, magnam tempore modi incidunt nulla ex ipsam officiis est alias amet aut atque repellat voluptatem. Eos dolorum quaerat doloribus.',
            urlImg: 'https://images2.imgbox.com/eb/0f/Vev7xkUX_o.png',
            id: '21',
            like: false,
        },
    ])

    function toggleLike(idx) {
        items[idx].like = !items[idx].like;
        forceUpdate();
    }
    return (
        <div className={S.list}>
            <div className="search" style={{height: 50, fontSize: 24, textAlign: 'center'}}>тут поиск</div>
            <div className="items">
                {items.map(({id, title, urlImg, description, like}, idx) => <ListItem
                    key={id}
                    title={title}
                    urlImg={urlImg}
                    description={description}
                    like={like}
                    onToggleLike={() => toggleLike(idx)}
                />)}
            </div>
        </div>
    )
}